REM start "" "C:\Windows\System32\SnippingTool.exe"
REM start "" "C:\Windows\System32\calc.exe"
start "" "C:\Program Files (x86)\Notepad++\notepad++.exe"
start "" "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
start "" "C:\Program Files\Microsoft Office\Office14\outlook.exe"
start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
start "" "C:\Users\eliasc\Downloads\eclipse-php-luna-SR1-win32-x86_64\eclipse\eclipse.exe"
start "" "C:\Users\eliasc\Desktop\Toolbox\AHK\hotstrings1.ahk"
start "" "C:\Users\eliasc\Desktop\Toolbox\AHK\UtilityScripts.ahk"
start "" "C:\Program Files\yWorks\yEd\yEd.exe"
start "" "C:\Program Files\Sublime Text 2\sublime_text.exe"
start "" "C:\wamp\wampmanager.exe"
cd "C:\Users\eliasc\workspace\app-berrystack"
vagrant up